import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globalicon.css";
import SessionAuthProvider from "@/context/useSessionAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classNames = [
    inter.className,
    "flex w-screen h-screen p-4 bg-[#DCD5E0] gap-4",
  ];

  return (
    <html lang="en">
      <body className={classNames.join(" ")}>
        <SessionAuthProvider>{children}</SessionAuthProvider>
      </body>
    </html>
  );
}
